# Generated by Django 5.0.7 on 2024-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
