# Generated by Django 5.0.7 on 2024-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gamer_id', models.IntegerField()),
                ('team_color', models.IntegerField()),
                ('wiapon_damage', models.IntegerField()),
                ('tager_type', models.IntegerField()),
                ('fire_count', models.IntegerField()),
                ('frags', models.IntegerField()),
                ('killed', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('ammo', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('game_time', models.DurationField()),
            ],
        ),
    ]
